### ISSUE TITLE
is this repository open to contribution?

### ISSUE THREAD

**Issue by aditya81070** [examples-org/Web-Workers#1]
@maddhruv can I contribute to the repository? What kind of examples will be committed here? I mean, you can find some example on MDN, etc. is there any particular requirement.

**Comment by maddhruv** [comment]
if you are asking specifically to this repository 
any example related to web workers - implementation, best practice, bugs, boilerplates
can reside here

or if at the level of organization, there will be several repositories based on frameworks, tools, APIs etc for examples

**Comment by aditya81070** [comment]
Okay got it. I would like to contribute

**Comment by maddhruv** [comment]
I am closing this
You can pick up any of the requested examples from issues
or raise an issues yourself if its not there
